1.Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [15]:
l1=[i for i in range(1,6)]
l1

[1, 2, 3, 4, 5]

In [16]:
# append
l1.append(6)
l1

[1, 2, 3, 4, 5, 6]

In [17]:
# extend
l2=[7,8,9]
l1.extend(l2)
l1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
#insert 
l1.insert(5,12)
l1

[1, 2, 3, 4, 5, 12, 6, 7, 8, 9]

In [19]:
#pop
l1.pop()
l1

[1, 2, 3, 4, 5, 12, 6, 7, 8]

In [20]:
#clear
l1.clear()
l1

[]

In [21]:
#count
l1=[2,3,4,5,6,7,4]
l1.count(4)

2

In [22]:
#index
l1.index(5)

3

In [23]:
#sort 
l1.sort()
l1

[2, 3, 4, 4, 5, 6, 7]

In [24]:
#reverse
l1.reverse()
l1

[7, 6, 5, 4, 4, 3, 2]

In [25]:
tup=('ishan','harsh','prem')

In [26]:
tup

('ishan', 'harsh', 'prem')

In [27]:
tup[1]='Mohit'
# this is happening because tuples are immutable that means once they are created they cannot be changed

TypeError: 'tuple' object does not support item assignment

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [28]:
set={2,3,1,2,3,2,3}
set
# so the output we get is sorted and does not have duplicate values in them

{1, 2, 3}

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [29]:
dictionary={'name':None,
           'age':None,
           'city':None}

dictionary.update({'age':22})
dictionary.update({'email':None})
dictionary

{'name': None, 'age': 22, 'city': None, 'email': None}

5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [30]:
age=int(input('Enter your age:'))

if age>=18:
    print('You are Eligible to vote')
else:
    print('You are not eligible to vote')

Enter your age:34
You are Eligible to vote


6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [31]:
marks=int(input('Enter marks:'))

if marks>=90 and marks<=100:
    print('A')
elif marks>=75 and marks<=89:
    print('B')
elif marks>=50 and marks<=74:
    print('C')
else:
    print('FAIL')

Enter marks:54
C


7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [33]:
num=int(input('Enter your Number:'))

if num>0 and num%2==0:
    print('Positive and Even')
elif num==0:
    print('Zero')
elif num>0:
    print('Positive')
else:
    print('Negative')

Enter your Number:45
Positive


8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [34]:
import numpy as np
scalar=np.array(5)
scalar

array(5)

In [35]:
np.array([x for x in range(1,6)])

array([1, 2, 3, 4, 5])

In [36]:
arr=np.array([x for x in range(10,61,10)])
arr.reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [37]:
import random
np.random.randint(0,100,size=(4,4))

array([[ 6, 73, 80, 31],
       [22, 53, 61, 58],
       [16, 80, 61, 85],
       [67, 72, 28, 13]])

Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [38]:
values=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [39]:
import pandas as pd
pd.DataFrame(values,columns=['A','B','C'])

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [49]:
data = {
    'Name': ['Aarav', 'Diya', 'Karan', 'Riya', 'Arjun', 'Meera', 'Kabir', 'Isha', 'Rohan', 'Tara'],
    'Age': [25, 28, 22, 24, 30, 27, 26, 29, 23, 31],
    'City': ['Delhi', 'Mumbai', 'Bangalore', 'Pune', 'Chennai', 'Hyderabad', 'Kolkata', 'Jaipur', 'Surat', 'Ahmedabad'],
    'Salary': [50000, 60000, 45000, 52000, 75000, 58000, 49000, 61000, 47000, 70000]
}

df=pd.DataFrame(data)

In [50]:
df

Name  Age       City  Salary
0  Aarav   25      Delhi   50000
1   Diya   28     Mumbai   60000
2  Karan   22  Bangalore   45000
3   Riya   24       Pune   52000
4  Arjun   30    Chennai   75000
5  Meera   27  Hyderabad   58000
6  Kabir   26    Kolkata   49000
7   Isha   29     Jaipur   61000
8  Rohan   23      Surat   47000
9   Tara   31  Ahmedabad   70000

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Age     10 non-null     int64 
 2   City    10 non-null     object
 3   Salary  10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes


In [52]:
df.describe()

Age       Salary
count  10.00000     10.00000
mean   26.50000  56700.00000
std     3.02765  10000.55554
min    22.00000  45000.00000
25%    24.25000  49250.00000
50%    26.50000  55000.00000
75%    28.75000  60750.00000
max    31.00000  75000.00000

In [53]:
df[['Name','City']]

Name       City
0  Aarav      Delhi
1   Diya     Mumbai
2  Karan  Bangalore
3   Riya       Pune
4  Arjun    Chennai
5  Meera  Hyderabad
6  Kabir    Kolkata
7   Isha     Jaipur
8  Rohan      Surat
9   Tara  Ahmedabad

In [55]:
df.drop('City',axis=1)

Name  Age  Salary
0  Aarav   25   50000
1   Diya   28   60000
2  Karan   22   45000
3   Riya   24   52000
4  Arjun   30   75000
5  Meera   27   58000
6  Kabir   26   49000
7   Isha   29   61000
8  Rohan   23   47000
9   Tara   31   70000

In [57]:
df.isnull().sum()
# there are no missing values in data 

Name      0
Age       0
City      0
Salary    0
dtype: int64

In [58]:
df.drop_duplicates()

Name  Age       City  Salary
0  Aarav   25      Delhi   50000
1   Diya   28     Mumbai   60000
2  Karan   22  Bangalore   45000
3   Riya   24       Pune   52000
4  Arjun   30    Chennai   75000
5  Meera   27  Hyderabad   58000
6  Kabir   26    Kolkata   49000
7   Isha   29     Jaipur   61000
8  Rohan   23      Surat   47000
9   Tara   31  Ahmedabad   70000

In [59]:
df.duplicated().sum()

0